name: Deploy develop

on:
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          version: '20'
      - uses: pnpm/action-setup@v4
        with:
          version: '10'

      - uses: darwinia-network/devops/actions/smart-vercel@main
        name: Deploy to Vercel
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          dist_path: out
          script_install: pnpm install
          script_build: pnpm run build
          project_name: kton-stake
          enable_cache: true
          enable_notify_comment: false
          enable_notify_slack: false
          slack_channel: public-ringdao-apps
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
